# Generated by Django 4.0.3 on 2022-03-19 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sudentregistration',
            options={'verbose_name': 'sudentRegistration', 'verbose_name_plural': 'Create student'},
        ),
        migrations.RemoveField(
            model_name='sudentregistration',
            name='User',
        ),
    ]
