# Generated by Django 4.0.3 on 2022-03-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal_app', '0002_alter_sudentregistration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sudentregistration',
            name='name',
            field=models.CharField(default=b'I01\n', max_length=150),
        ),
    ]
