# Generated by Django 4.0.3 on 2022-03-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal_app', '0003_sudentregistration_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sudentregistration',
            name='std',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
