# Generated by Django 4.0.3 on 2022-04-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal_app', '0006_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='phonenumber',
            field=models.TextField(default=None, max_length=200),
        ),
    ]
